var gKeywordSearchCountMap = { 'funny': 12, 'cat': 16, 'baby': 2 }
var gLineNum = 1
var gImgs = [
    { id: 1, url: 'imgs/1.jpg', keywords: ['funny', 'tramp'] },
    { id: 2, url: './imgs/2.jpg', keywords: ['puppy', 'happy'] },
    { id: 3, url: './imgs/3.jpg', keywords: ['happy'] },
    { id: 4, url: './imgs/4.jpg', keywords: ['happy'] },
    { id: 5, url: './imgs/5.jpg', keywords: ['happy'] },
    { id: 6, url: './imgs/6.jpg', keywords: ['happy'] },
    { id: 7, url: './imgs/7.jpg', keywords: ['happy'] },
    { id: 8, url: './imgs/8.jpg', keywords: ['happy'] },
    { id: 9, url: './imgs/9.jpg', keywords: ['happy'] },
    { id: 10, url: './imgs/10.jpg', keywords: ['happy'] },
    { id: 11, url: './imgs/11.jpg', keywords: ['happy'] },
    { id: 12, url: './imgs/12.jpg', keywords: ['happy'] },
    { id: 13, url: './imgs/13.jpg', keywords: ['happy'] },
    { id: 14, url: './imgs/14.jpg', keywords: ['happy'] },
    { id: 15, url: './imgs/15.jpg', keywords: ['happy'] },
    { id: 16, url: './imgs/16.jpg', keywords: ['happy'] },
    { id: 17, url: './imgs/17.jpg', keywords: ['happy'] },
    { id: 18, url: './imgs/18.jpg', keywords: ['happy'] },
]






var gMeme = {
    selectedImgId: 5,
    selectedLineIdx: 0,
    lines: [
        {
            txt: 'I sometimes eat Falafel',
            size: 20,
            color: 'red',
            pos: { x: 200, y: 65 },
        }
    ]
}
